//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Scenarios = new HashSet<Scenario>();
            this.Users = new HashSet<User>();
        }
    
        public int mId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Scenario> Scenarios { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
