//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public Scenario()
        {
            this.TestCases = new HashSet<TestCas>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public string Importance { get; set; }
        public int Module_mId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<TestCas> TestCases { get; set; }
    }
}
