//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCas
    {
        public TestCas()
        {
            this.TestDatas = new HashSet<TestData>();
            this.Users = new HashSet<User>();
        }
    
        public int tcId { get; set; }
        public string Name { get; set; }
        public string TCode { get; set; }
        public string ScreenTitle { get; set; }
        public string Step { get; set; }
        public string Precondition { get; set; }
        public string ExpectedResult { get; set; }
        public string ActualResult { get; set; }
        public string PassFail { get; set; }
        public int ScenarioId { get; set; }
    
        public virtual Scenario Scenario { get; set; }
        public virtual ICollection<TestData> TestDatas { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
