//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData
    {
        public TestData()
        {
            this.Users = new HashSet<User>();
        }
    
        public int tdId { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string Value { get; set; }
        public string PassFail { get; set; }
        public int TestCase_tcId { get; set; }
    
        public virtual TestCas TestCas { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
