//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UATSytemDbEntities : DbContext
    {
        public UATSytemDbEntities()
            : base("name=UATSytemDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Scenario> Scenarios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestCas> TestCases { get; set; }
        public virtual DbSet<TestData> TestDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
